spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:temp;DB_CLOSE_DELAY=-1

server:
  port: 8090

centroid:
  app:
    jwtSecret: centroidSecretKey
    jwtExpirationSeconds: 1296000
    refreshExpiryDays: 30

