spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console.enabled: true
  datasource:
    url: jdbc:mysql://192.168.0.145:3306/centroid
    username: admin
    password: Admin@123

server:
  port: 8090

centroid:
  app:
    jwtSecret: centroidSecretKey
    jwtExpirationSeconds: 1296000
    refreshExpiryDays: 30

